---

name: fedora_faiss

# Define the GPU deployment configuration alias
x-gpu-deploy-config: &gpu-deploy-config
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all # Use 'all' GPUs for the test
            capabilities: [gpu]


services:
  fedora-40-faiss:
    image: tolland/fedora-faiss:40
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-40-gpu/Dockerfile
    <<: *gpu-deploy-config
    profiles:
      - build
      - f40

  fedora-41-faiss-builder:
    image: tolland/fedora-41-faiss-builder:latest
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-41-faiss-builder/Dockerfile

  fedora-41-faiss-gpu:
    image: tolland/fedora-faiss:41
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-41-gpu/Dockerfile
    depends_on:
      - fedora-41-faiss-builder
    profiles:
      - build

  fedora-41-faiss-work:
    image: tolland/fedora-41-faiss-builder:latest
    pull_policy: build
    user: ${FAISS_BUILD_USER:-1000}:${FAISS_BUILD_GROUP:-1000}
    volumes:
      - ./third_party/faiss:/faiss:z
      - ./third_party/faiss_install:/app:z
      - ./scripts:/scripts:z
      # - ./context/build.sh:/scripts/build.sh:z
