---

name: fedora_faiss

# Define the GPU deployment configuration alias
x-gpu-deploy-config: &gpu-deploy-config
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all # Use 'all' GPUs for the test
            capabilities: [gpu]


services:
  fedora-40-faiss:
    image: tolland/fedora-faiss:40
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-40-gpu/Dockerfile
    <<: *gpu-deploy-config

  fedora-41-faiss:
    image: tolland/fedora-faiss:41
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-41-gpu/Dockerfile
    <<: *gpu-deploy-config

