---

name: faiss_fedora


services:
  fedora41-cuda-runfile:
    # container_name: jenkins
    build:
      context: ./docker
      dockerfile: fedora41-cuda-runfile/Dockerfile
      additional_contexts:
        cuda_installer: ./cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  faiss-test:
    # container_name: jenkins
    build:
      context: ./docker
      dockerfile: faiss_test/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
