---

name: fedora_faiss


services:
  faiss-test:
    # container_name: jenkins
    build:
      context: ./faiss_test
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
