---

name: fedora-base

services:
  fedora-40-base:
    image: tolland/fedora:40
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-40-base/Dockerfile

  fedora-40-builder:
    image: tolland/fedora-builder:40
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-40-builder/Dockerfile

  fedora-40-builder-kmod:
    image: tolland/fedora-builder-kmod:40
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-40-builder-kmod/Dockerfile

  fedora-41-base:
    image: tolland/fedora:41
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-41-base/Dockerfile

  fedora-41-builder:
    image: tolland/fedora-builder:41
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-41-builder/Dockerfile

  fedora-41-builder-kmod:
    image: tolland/fedora-builder-kmod:41
    pull_policy: build
    build:
      context: ./context
      dockerfile: ../fedora-41-builder-kmod/Dockerfile
